"""
Django settings for tillweb project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Since this project is packaged as a library and installed into a
# venv, this settings file can't change from one installation to
# another. Instead, a configuration file is read from an external location.
from tillweb.config.conffile import read_config
from pathlib import Path
import requests
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from django.urls import reverse
from django.contrib.messages import constants as messages

config = read_config()
django_config = config['django']
front_page_config = config['front-page']
till_config = config['till']
oidc_config = config['oidc']

# Simple switch to disable OIDC configuration without deleting it from
# the configuration file
if not oidc_config.get("enabled", True):
    oidc_config = {}

# Build paths inside the project like this:
# BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1@q-55(ppk-*j65!%0b7&0-8_ahydtyz8dkv&lm=%zw(9ymk'
if scf := django_config.get("secret_key_file"):
    with open(scf) as f:
        SECRET_KEY = f.read().strip()

# SECURITY WARNING: don't run with debug turned on in production!
# In production, this will be overridden in settings_production.py
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bootstrap_breadcrumbs',
    'widget_tweaks',
    'quicktill.tillweb',
]
if oidc_config:
    INSTALLED_APPS.append('mozilla_django_oidc')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if oidc_config:
    MIDDLEWARE.append('mozilla_django_oidc.middleware.SessionRefresh')


ROOT_URLCONF = 'tillweb.config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tillweb.config.context_processors.pubname_setting',
            ],
        },
    },
]
if oidc_config:
    TEMPLATES[0]['OPTIONS']['context_processors'].append(
        'tillweb.config.oidc.context_processor')

WSGI_APPLICATION = 'tillweb.config.wsgi.application'


# Messages system: set Bootstrap theme tags for message tags
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-primary',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': f'django.db.backends.'
        f'{django_config.get("database_engine", 'sqlite3')}',
        'NAME': django_config.get(
            "database_name", BASE_DIR.parent / 'tillweb_db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.'
        'UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
        'MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
        'CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
        'NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
if oidc_config:
    AUTHENTICATION_BACKENDS.append(
        'tillweb.config.oidc.TillOIDCAuthenticationBackend')


if oidc_config:
    if "configuration_url" in oidc_config:
        cfg = requests.get(oidc_config["configuration_url"]).json()
    else:
        cfg = {}
    OIDC_OP_AUTHORIZATION_ENDPOINT = \
        oidc_config.get("authorization_endpoint") \
        or cfg["authorization_endpoint"]
    OIDC_OP_TOKEN_ENDPOINT = \
        oidc_config.get("token_endpoint") \
        or cfg["token_endpoint"]
    OIDC_OP_USER_ENDPOINT = \
        oidc_config.get("userinfo_endpoint") \
        or cfg["userinfo_endpoint"]
    OIDC_OP_JWKS_ENDPOINT = \
        oidc_config.get("jwks_endpoint") \
        or cfg["jwks_uri"]
    OIDC_RP_CLIENT_ID = oidc_config["client_id"]
    with open(oidc_config["client_secret_file"]) as f:
        OIDC_RP_CLIENT_SECRET = f.read().strip()
    OIDC_RP_SIGN_ALGO = oidc_config.get("token_signing_algorithm", 'RS256')
    OIDC_RP_SCOPES = "openid email profile groups"
    OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS = oidc_config.get(
        "token_refresh_interval", 3600)

    OIDC_CALLBACK_CLASS = 'tillweb.config.oidc.' \
        'TillOIDCAuthenticationCallbackView'
    LOGIN_REDIRECT_URL = "/"
    LOGIN_REDIRECT_URL_FAILURE = "/accounts/login/failure/"
    # LOGOUT_REDIRECT_URL = ""

    OIDC_PROVIDER_NAME = oidc_config.get("provider_name", "OpenID Connect")
    OIDC_REQUIRED_GROUPS = oidc_config["required_groups"]
    OIDC_SUPERUSER_GROUPS = oidc_config["superuser_groups"]
    OIDC_STAFF_GROUPS = oidc_config["staff_groups"]
    OIDC_USER_HOME_PAGE_TEMPLATE = oidc_config.get(
        "user_home_page_template", "")

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = django_config.get("language_code", 'en-GB')

TIME_ZONE = django_config.get("time_zone", 'UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Media files (uploaded by users)
MEDIA_URL = 'media/'


FRONT_PAGE_MODE = front_page_config.get("mode", "start-button")


# Configure quicktill.tillweb
# info["reverse"] still needs the django reverse function passing
TILLWEB_DATABASE = sessionmaker(
    bind=create_engine(
        f'postgresql+psycopg2:///{till_config["database_name"]}',
        pool_size=32, pool_recycle=600, future=True),
    info={'reverse': reverse}, future=True)
TILLWEB_PUBNAME = till_config.get("site_name", "site_name not configured")
TILLWEB_LOGIN_REQUIRED = True
TILLWEB_DEFAULT_ACCESS = "M"
TILLWEB_MONEY_SYMBOL = till_config.get("currency_symbol", "")
